services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=week27
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    container_name: server
    ports:
      - 3003:3003
    environment:
      - DATABASE_URL="postgresql://postgres:mysecretpassword@postgres:5432/week27?schema=public"
    depends_on:
      postgres:
        condition: service_healthy

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.web
      args:
        - DB_URL="postgresql://postgres:mysecretpassword@postgres:5432/week27?schema=public"
      network: host
    container_name: web
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL="postgresql://postgres:mysecretpassword@postgres:5432/week27?schema=public"
    depends_on:
      postgres:
        condition: service_healthy

  ws:
    build:
      context: .
      dockerfile: docker/Dockerfile.ws
    ports:
      - 8080:8080
    container_name: ws
    environment:
      - DATABASE_URL="postgresql://postgres:mysecretpassword@postgres:5432/week27?schema=public"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: