version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    ports:
      - 3003:3003
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@postgres:5432/week-27.2
    depends_on:
      - postgres

  # web:
  #   build:
  #     context: .
  #     dockerfile: docker/Dockerfile.web
  #     args:
  #       DATABASE_URL: "postgresql://postgres:mysecretpassword@postgres:5432/week-27.2"
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:mysecretpassword@postgres:5432/week-27.2
  #   depends_on:
  #     - postgres

  ws:
    build:
      context: .
      dockerfile: docker/Dockerfile.ws
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@postgres:5432/week-27.2
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB:week-27.2
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: