services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    ports:
      - 3003:3003
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@postgres:5432/postgres
    depends_on:
      postgres:
        condition: service_healthy

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.web
      args:
        - DATABASE_URL=postgresql://postgres:mysecretpassword@postgres:5432/postgres
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@postgres:5432/postgres
    depends_on:
      postgres:
        condition: service_healthy

  ws:
    build:
      context: .
      dockerfile: docker/Dockerfile.ws
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@postgres:5432/postgres
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: