FROM oven/bun:latest

# ARG DATABASE_URL
# ENV DATABASE_URL=${DATABASE_URL}

WORKDIR /usr/src/app

RUN apt-get update -y && apt-get install -y openssl

# Copy package files first for better caching
COPY package.json /usr/src/app
COPY turbo.json /usr/src/app
COPY bun.lockb /usr/src/app

# Copy workspace packages
COPY ./packages /usr/src/app/packages
COPY ./apps/web /usr/src/app/apps/web

# Install dependencies and build
RUN bun install
RUN bun run db:generate
# RUN cd /usr/src/app/packages/db
# ENV DATABASE_URL=$DATABASE_URL
# RUN echo "DATABASE_URL=$DATABASE_URL" > .env

WORKDIR /usr/src/app/apps/web

# RUN DATABASE_URL=$DATABASE_URL bun run build
# RUN bun run build

EXPOSE 3000

WORKDIR /usr/src/app

CMD ["bun", "run", "dev:docker"]