FROM oven/bun:latest

WORKDIR /usr/src/app

RUN apt-get update -y && apt-get install -y openssl

ARG DB_URL
ENV DATABASE_URL=${DB_URL}

COPY ./packages ./packages
COPY ./bun.lockb ./bun.lockb

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/web ./apps/web

RUN bun install
RUN bun run db:generate
RUN DATABASE_URL=${DB_URL} bun run build

EXPOSE 3000

CMD ["bun", "run", "start:web"]