FROM oven/bun:latest

ARG DATABASE_URL

WORKDIR /usr/src/app

RUN apt-get update -y && apt-get install -y openssl

COPY ./packages ./packages
COPY ./bun.lockb ./bun.lockb

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

RUN bun install

COPY ./apps/server ./apps/server

RUN cd /usr/src/app/packages/db
ENV DATABASE_URL=$DATABASE_URL
RUN bun run db:generate

EXPOSE 3003

WORKDIR /usr/src/app

CMD ["bun", "run", "start:server"]