FROM oven/bun:latest

WORKDIR /usr/src/app

RUN apt-get update -y && apt-get install -y openssl

COPY ./packages ./packages
COPY ./bun.lockb ./bun.lockb

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/server ./apps/server

RUN bun install
RUN bun run db:generate

EXPOSE 3003

WORKDIR /usr/src/app

CMD ["bun", "run", "start:server"]